"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['TransPad.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'CFBundleIdentifier': 'com.rexzhang.TransPad',
        'LSUIElement': True,
        'NSServices': [
            {
                'NSMenuItem': {
                    'default': 'TransPad: Translate',
                    'Chinese': 'TransPad: 翻译文本',
                    'English': 'TransPad: Translate Text',
                },
                'NSMessage': 'translateTextService',
                'NSPortName': 'TransPadService',
                'NSReturnTypes': ['NSStringPboardType'],
                'NSSendTypes': ['NSStringPboardType'],
            },
        ],
    },
    'packages': ['rumps'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
